### ISSUE TITLE
Write to a file

### ISSUE THREAD

**Issue by naresh217** [DiegoZoracKy/convert-excel-to-json#10]
Do you have any option to write to a file while using CLI.

I tried to use it in my angular project using but it throws an error
`'use strict';
const excelToJson = require('convert-excel-to-json');

const result = excelToJson({
	sourceFile: 'SOME-EXCEL-FILE.xlsx'
});`
![image](https://user-images.githubusercontent.com/5828286/42464287-9ca0f4f8-8376-11e8-96e1-9c72b1143080.png)

**Comment by DiegoZoracKy** [comment]
This module uses js-xlsx under the hood. Check if it supports running on browser and I found this thread that may help you:

https://github.com/SheetJS/js-xlsx/issues/418

**Comment by naresh217** [comment]
@DiegoZoracKy do you have an option to write to a file using command line ?

`$ convert-excel-to-json --config='{"sourceFile": "tests/test-data.xlsx", "outputJSON": true}'`

**Comment by DiegoZoracKy** [comment]
@naresh217 no, at first, because when using via CLI we can easily use Redirection `>` to write a file containing the output data.

Example: 

`$ convert-excel-to-json --config='{"sourceFile": "tests/test-data.xlsx", "outputJSON": true}' > output-file.json`

Sorry about the first answer. I was walking on the street and ended up focusing on the browser error.

**Comment by naresh217** [comment]
Thankyou. With this approach generated output file failing jsonlint.com
testing

**Comment by DiegoZoracKy** [comment]
Can you paste here a snippet of what was generated.

**Comment by naresh217** [comment]
Input [test-data.xlsx](https://github.com/DiegoZoracKy/convert-excel-to-json/files/2177642/test-data.xlsx)
**Generated output** 
{
	"sheet1": [
		{
			"A": "id",
			"B": "first_name",
			"C": "last_name",
			"D": "email",
			"E": "gender",
			"F": "ip_address"
		},
		{
			"A": 1,
			"B": "Judith",
			"C": "Bennett",
			"D": "jbennett0@cargocollective.com",
			"E": "Female",
			"F": "190.37.72.226"
		},
		{
			"A": 2,
			"B": "Denise",
			"C": "Ramirez",
			"D": "dramirez1@woothemes.com",
			"E": "Female",
			"F": "13.63.225.90"
		},
		{
			"A": 3,
			"B": "Antonio",
			"C": "Henderson",
			"D": "ahenderson2@mapquest.com",
			"E": "Male",
			"F": "186.224.18.54"
		},
		{
			"A": 4,
			"B": "Matthew",
			"C": "Jacobs",
			"D": "mjacobs3@hatena.ne.jp",
			"E": "Male",
			"F": "71.115.204.8"
		},
		{
			"A": 5,
			"B": "Jacqueline",
			"C": "Hawkins",
			"D": "jhawkins4@usatoday.com",
			"E": "Female",
			"F": "112.161.144.113"
		},
		{
			"A": 6,
			"B": "Betty",
			"C": "George",
			"D": "bgeorge5@cnbc.com",
			"E": "Female",
			"F": "151.9.214.150"
		},
		{
			"A": 7,
			"B": "Nicholas",
			"C": "Cole",
			"D": "ncole6@digg.com",
			"E": "Male",
			"F": "130.113.34.123"
		},
		{
			"A": 8,
			"B": "Christina",
			"C": "Fields",
			"D": "cfields7@icio.us",
			"E": "Female",
			"F": "158.175.78.96"
		},
		{
			"A": 9,
			"B": "John",
			"C": "Cole",
			"D": "jcole8@github.com",
			"E": "Male",
			"F": "87.198.248.122"
		},
		{
			"A": 10,
			"B": "Carolyn",
			"C": "Marshall",
			"D": "cmarshall9@acquirethisname.com",
			"E": "Female",
			"F": "169.241.125.206"
		},
		{
			"A": 11,
			"B": "Albert",
			"C": "Schmidt",
			"D": "aschmidta@imdb.com",
			"E": "Male",
			"F": "82.36.174.49"
		},
		{
			"A": 12,
			"B": "Lillian",
			"C": "Bennett",
			"D": "lbennettb@ca.gov",
			"E": "Female",
			"F": "227.130.226.191"
		},
		{
			"A": 13,
			"B": "Kathy",
			"C": "Payne",
			"D": "kpaynec@mozilla.org",
			"E": "Female",
			"F": "189.92.180.236"
		},
		{
			"A": 14,
			"B": "Jack",
			"C": "Ferguson",
			"D": "jfergusond@youku.com",
			"E": "Male",
			"F": "237.228.12.35"
		},
		{
			"A": 15,
			"B": "Jean",
			"C": "Gordon",
			"D": "jgordone@tinypic.com",
			"E": "Female",
			"F": "82.238.48.246"
		},
		{
			"A": 16,
			"B": "John",
			"C": "Clark",
			"D": "jclarkf@google.com",
			"E": "Male",
			"F": "43.126.79.189"
		},
		{
			"A": 17,
			"B": "Pamela",
			"C": "Gilbert",
			"D": "pgilbertg@china.com.cn",
			"E": "Female",
			"F": "22.163.47.237"
		},
		{
			"A": 18,
			"B": "Deborah",
			"C": "Banks",
			"D": "dbanksh@umn.edu",
			"E": "Female",
			"F": "221.123.73.42"
		},
		{
			"A": 19,
			"B": "Emily",
			"C": "Hamilton",
			"D": "ehamiltoni@craigslist.org",
			"E": "Female",
			"F": "30.169.177.251"
		},
		{
			"A": 20,
			"B": "Katherine",
			"C": "Jones",
			"D": "kjonesj@behance.net",
			"E": "Female",
			"F": "228.11.87.66"
		},
		{
			"A": 21,
			"B": "Ruby",
			"C": "Stanley",
			"D": "rstanleyk@w3.org",
			"E": "Female",
			"F": "60.65.225.158"
		},
		{
			"A": 22,
			"B": "Juan",
			"C": "Pierce",
			"D": "jpiercel@miitbeian.gov.cn",
			"E": "Male",
			"F": "116.251.134.70"
		},
		{
			"A": 23,
			"B": "Rachel",
			"C": "Long",
			"D": "rlongm@usnews.com",
			"E": "Female",
			"F": "137.30.106.203"
		},
		{
			"A": 24,
			"B": "Debra",
			"C": "Oliver",
			"D": "dolivern@yolasite.com",
			"E": "Female",
			"F": "187.87.117.203"
		}
	],
	"sheet2": [
		{
			"A": "id",
			"B": "first_name",
			"C": "last_name",
			"D": "email",
			"E": "gender",
			"F": "ip_address"
		},
		{
			"A": 25,
			"B": "Jack",
			"C": "Bishop",
			"D": "jbishopo@businessinsider.com",
			"E": "Male",
			"F": "154.11.84.148"
		},
		{
			"A": 26,
			"B": "Alice",
			"C": "Cook",
			"D": "acookp@theatlantic.com",
			"E": "Female",
			"F": "253.251.171.169"
		},
		{
			"A": 27,
			"B": "Denise",
			"C": "Hart",
			"D": "dhartq@free.fr",
			"E": "Female",
			"F": "41.7.18.202"
		},
		{
			"A": 28,
			"B": "Susan",
			"C": "Oliver",
			"D": "soliverr@narod.ru",
			"E": "Female",
			"F": "30.73.25.111"
		},
		{
			"A": 29,
			"B": "Christopher",
			"C": "Watson",
			"D": "cwatsons@ibm.com",
			"E": "Male",
			"F": "237.207.183.205"
		},
		{
			"A": 30,
			"B": "Howard",
			"C": "Ray",
			"D": "hrayt@typepad.com",
			"E": "Male",
			"F": "110.31.192.119"
		},
		{
			"A": 31,
			"B": "Doris",
			"C": "Banks",
			"D": "dbanksu@tripod.com",
			"E": "Female",
			"F": "93.158.23.15"
		},
		{
			"A": 32,
			"B": "Tammy",
			"C": "Duncan",
			"D": "tduncanv@who.int",
			"E": "Female",
			"F": "36.223.211.101"
		},
		{
			"A": 33,
			"B": "Brandon",
			"C": "Nelson",
			"D": "bnelsonw@nsw.gov.au",
			"E": "Male",
			"F": "149.230.247.47"
		},
		{
			"A": 34,
			"B": "Janice",
			"C": "Banks",
			"D": "jbanksx@reverbnation.com",
			"E": "Female",
			"F": "225.10.207.129"
		},
		{
			"A": 35,
			"B": "Randy",
			"C": "Gardner",
			"D": "rgardnery@cdc.gov",
			"E": "Male",
			"F": "136.250.243.202"
		},
		{
			"A": 36,
			"B": "Denise",
			"C": "Burton",
			"D": "dburtonz@timesonline.co.uk",
			"E": "Female",
			"F": "254.185.104.57"
		},
		{
			"A": 37,
			"B": "Paul",
			"C": "Rogers",
			"D": "progers10@npr.org",
			"E": "Male",
			"F": "188.219.107.207"
		},
		{
			"A": 38,
			"B": "Johnny",
			"C": "Fernandez",
			"D": "jfernandez11@amazonaws.com",
			"E": "Male",
			"F": "233.164.136.180"
		},
		{
			"A": 39,
			"B": "Jane",
			"C": "Mason",
			"D": "jmason12@phpbb.com",
			"E": "Female",
			"F": "156.240.141.240"
		},
		{
			"A": 40,
			"B": "Scott",
			"C": "Day",
			"D": "sday13@prnewswire.com",
			"E": "Male",
			"F": "154.188.18.107"
		},
		{
			"A": 41,
			"B": "Philip",
			"C": "White",
			"D": "pwhite14@exblog.jp",
			"E": "Male",
			"F": "73.100.195.152"
		},
		{
			"A": 42,
			"B": "Kenneth",
			"C": "Duncan",
			"D": "kduncan15@people.com.cn",
			"E": "Male",
			"F": "105.112.16.103"
		},
		{
			"A": 43,
			"B": "Joseph",
			"C": "Price",
			"D": "jprice16@cmu.edu",
			"E": "Male",
			"F": "33.92.219.103"
		},
		{
			"A": 44,
			"B": "Edward",
			"C": "Howard",
			"D": "ehoward17@businessinsider.com",
			"E": "Male",
			"F": "38.179.117.21"
		},
		{
			"A": 45,
			"B": "Frances",
			"C": "Wells",
			"D": "fwells18@slashdot.org",
			"E": "Female",
			"F": "75.126.73.137"
		},
		{
			"A": 46,
			"B": "Ashley",
			"C": "Davis",
			"D": "adavis19@slideshare.net",
			"E": "Female",
			"F": "73.140.223.76"
		},
		{
			"A": 47,
			"B": "Clarence",
			"C": "Hicks",
			"D": "chicks1a@epa.gov",
			"E": "Male",
			"F": "92.13.200.140"
		},
		{
			"A": 48,
			"B": "Sharon",
			"C": "Stone",
			"D": "sstone1b@biblegateway.com",
			"E": "Female",
			"F": "38.83.41.214"
		},
		{
			"A": 49,
			"B": "Scott",
			"C": "Shaw",
			"D": "sshaw1c@senate.gov",
			"E": "Male",
			"F": "84.180.189.90"
		},
		{
			"A": 50,
			"B": "Susan",
			"C": "Miller",
			"D": "smiller1d@china.com.cn",
			"E": "Female",
			"F": "244.232.244.90"
		}
	]
}
{ sheet1:
   [ { A: 'id',
       B: 'first_name',
       C: 'last_name',
       D: 'email',
       E: 'gender',
       F: 'ip_address' },
     { A: 1,
       B: 'Judith',
       C: 'Bennett',
       D: 'jbennett0@cargocollective.com',
       E: 'Female',
       F: '190.37.72.226' },
     { A: 2,
       B: 'Denise',
       C: 'Ramirez',
       D: 'dramirez1@woothemes.com',
       E: 'Female',
       F: '13.63.225.90' },
     { A: 3,
       B: 'Antonio',
       C: 'Henderson',
       D: 'ahenderson2@mapquest.com',
       E: 'Male',
       F: '186.224.18.54' },
     { A: 4,
       B: 'Matthew',
       C: 'Jacobs',
       D: 'mjacobs3@hatena.ne.jp',
       E: 'Male',
       F: '71.115.204.8' },
     { A: 5,
       B: 'Jacqueline',
       C: 'Hawkins',
       D: 'jhawkins4@usatoday.com',
       E: 'Female',
       F: '112.161.144.113' },
     { A: 6,
       B: 'Betty',
       C: 'George',
       D: 'bgeorge5@cnbc.com',
       E: 'Female',
       F: '151.9.214.150' },
     { A: 7,
       B: 'Nicholas',
       C: 'Cole',
       D: 'ncole6@digg.com',
       E: 'Male',
       F: '130.113.34.123' },
     { A: 8,
       B: 'Christina',
       C: 'Fields',
       D: 'cfields7@icio.us',
       E: 'Female',
       F: '158.175.78.96' },
     { A: 9,
       B: 'John',
       C: 'Cole',
       D: 'jcole8@github.com',
       E: 'Male',
       F: '87.198.248.122' },
     { A: 10,
       B: 'Carolyn',
       C: 'Marshall',
       D: 'cmarshall9@acquirethisname.com',
       E: 'Female',
       F: '169.241.125.206' },
     { A: 11,
       B: 'Albert',
       C: 'Schmidt',
       D: 'aschmidta@imdb.com',
       E: 'Male',
       F: '82.36.174.49' },
     { A: 12,
       B: 'Lillian',
       C: 'Bennett',
       D: 'lbennettb@ca.gov',
       E: 'Female',
       F: '227.130.226.191' },
     { A: 13,
       B: 'Kathy',
       C: 'Payne',
       D: 'kpaynec@mozilla.org',
       E: 'Female',
       F: '189.92.180.236' },
     { A: 14,
       B: 'Jack',
       C: 'Ferguson',
       D: 'jfergusond@youku.com',
       E: 'Male',
       F: '237.228.12.35' },
     { A: 15,
       B: 'Jean',
       C: 'Gordon',
       D: 'jgordone@tinypic.com',
       E: 'Female',
       F: '82.238.48.246' },
     { A: 16,
       B: 'John',
       C: 'Clark',
       D: 'jclarkf@google.com',
       E: 'Male',
       F: '43.126.79.189' },
     { A: 17,
       B: 'Pamela',
       C: 'Gilbert',
       D: 'pgilbertg@china.com.cn',
       E: 'Female',
       F: '22.163.47.237' },
     { A: 18,
       B: 'Deborah',
       C: 'Banks',
       D: 'dbanksh@umn.edu',
       E: 'Female',
       F: '221.123.73.42' },
     { A: 19,
       B: 'Emily',
       C: 'Hamilton',
       D: 'ehamiltoni@craigslist.org',
       E: 'Female',
       F: '30.169.177.251' },
     { A: 20,
       B: 'Katherine',
       C: 'Jones',
       D: 'kjonesj@behance.net',
       E: 'Female',
       F: '228.11.87.66' },
     { A: 21,
       B: 'Ruby',
       C: 'Stanley',
       D: 'rstanleyk@w3.org',
       E: 'Female',
       F: '60.65.225.158' },
     { A: 22,
       B: 'Juan',
       C: 'Pierce',
       D: 'jpiercel@miitbeian.gov.cn',
       E: 'Male',
       F: '116.251.134.70' },
     { A: 23,
       B: 'Rachel',
       C: 'Long',
       D: 'rlongm@usnews.com',
       E: 'Female',
       F: '137.30.106.203' },
     { A: 24,
       B: 'Debra',
       C: 'Oliver',
       D: 'dolivern@yolasite.com',
       E: 'Female',
       F: '187.87.117.203' } ],
  sheet2:
   [ { A: 'id',
       B: 'first_name',
       C: 'last_name',
       D: 'email',
       E: 'gender',
       F: 'ip_address' },
     { A: 25,
       B: 'Jack',
       C: 'Bishop',
       D: 'jbishopo@businessinsider.com',
       E: 'Male',
       F: '154.11.84.148' },
     { A: 26,
       B: 'Alice',
       C: 'Cook',
       D: 'acookp@theatlantic.com',
       E: 'Female',
       F: '253.251.171.169' },
     { A: 27,
       B: 'Denise',
       C: 'Hart',
       D: 'dhartq@free.fr',
       E: 'Female',
       F: '41.7.18.202' },
     { A: 28,
       B: 'Susan',
       C: 'Oliver',
       D: 'soliverr@narod.ru',
       E: 'Female',
       F: '30.73.25.111' },
     { A: 29,
       B: 'Christopher',
       C: 'Watson',
       D: 'cwatsons@ibm.com',
       E: 'Male',
       F: '237.207.183.205' },
     { A: 30,
       B: 'Howard',
       C: 'Ray',
       D: 'hrayt@typepad.com',
       E: 'Male',
       F: '110.31.192.119' },
     { A: 31,
       B: 'Doris',
       C: 'Banks',
       D: 'dbanksu@tripod.com',
       E: 'Female',
       F: '93.158.23.15' },
     { A: 32,
       B: 'Tammy',
       C: 'Duncan',
       D: 'tduncanv@who.int',
       E: 'Female',
       F: '36.223.211.101' },
     { A: 33,
       B: 'Brandon',
       C: 'Nelson',
       D: 'bnelsonw@nsw.gov.au',
       E: 'Male',
       F: '149.230.247.47' },
     { A: 34,
       B: 'Janice',
       C: 'Banks',
       D: 'jbanksx@reverbnation.com',
       E: 'Female',
       F: '225.10.207.129' },
     { A: 35,
       B: 'Randy',
       C: 'Gardner',
       D: 'rgardnery@cdc.gov',
       E: 'Male',
       F: '136.250.243.202' },
     { A: 36,
       B: 'Denise',
       C: 'Burton',
       D: 'dburtonz@timesonline.co.uk',
       E: 'Female',
       F: '254.185.104.57' },
     { A: 37,
       B: 'Paul',
       C: 'Rogers',
       D: 'progers10@npr.org',
       E: 'Male',
       F: '188.219.107.207' },
     { A: 38,
       B: 'Johnny',
       C: 'Fernandez',
       D: 'jfernandez11@amazonaws.com',
       E: 'Male',
       F: '233.164.136.180' },
     { A: 39,
       B: 'Jane',
       C: 'Mason',
       D: 'jmason12@phpbb.com',
       E: 'Female',
       F: '156.240.141.240' },
     { A: 40,
       B: 'Scott',
       C: 'Day',
       D: 'sday13@prnewswire.com',
       E: 'Male',
       F: '154.188.18.107' },
     { A: 41,
       B: 'Philip',
       C: 'White',
       D: 'pwhite14@exblog.jp',
       E: 'Male',
       F: '73.100.195.152' },
     { A: 42,
       B: 'Kenneth',
       C: 'Duncan',
       D: 'kduncan15@people.com.cn',
       E: 'Male',
       F: '105.112.16.103' },
     { A: 43,
       B: 'Joseph',
       C: 'Price',
       D: 'jprice16@cmu.edu',
       E: 'Male',
       F: '33.92.219.103' },
     { A: 44,
       B: 'Edward',
       C: 'Howard',
       D: 'ehoward17@businessinsider.com',
       E: 'Male',
       F: '38.179.117.21' },
     { A: 45,
       B: 'Frances',
       C: 'Wells',
       D: 'fwells18@slashdot.org',
       E: 'Female',
       F: '75.126.73.137' },
     { A: 46,
       B: 'Ashley',
       C: 'Davis',
       D: 'adavis19@slideshare.net',
       E: 'Female',
       F: '73.140.223.76' },
     { A: 47,
       B: 'Clarence',
       C: 'Hicks',
       D: 'chicks1a@epa.gov',
       E: 'Male',
       F: '92.13.200.140' },
     { A: 48,
       B: 'Sharon',
       C: 'Stone',
       D: 'sstone1b@biblegateway.com',
       E: 'Female',
       F: '38.83.41.214' },
     { A: 49,
       B: 'Scott',
       C: 'Shaw',
       D: 'sshaw1c@senate.gov',
       E: 'Male',
       F: '84.180.189.90' },
     { A: 50,
       B: 'Susan',
       C: 'Miller',
       D: 'smiller1d@china.com.cn',
       E: 'Female',
       F: '244.232.244.90' } ] }
{ sheet1:
   [ { A: 'id',
       B: 'first_name',
       C: 'last_name',
       D: 'email',
       E: 'gender',
       F: 'ip_address' },
     { A: 1,
       B: 'Judith',
       C: 'Bennett',
       D: 'jbennett0@cargocollective.com',
       E: 'Female',
       F: '190.37.72.226' },
     { A: 2,
       B: 'Denise',
       C: 'Ramirez',
       D: 'dramirez1@woothemes.com',
       E: 'Female',
       F: '13.63.225.90' },
     { A: 3,
       B: 'Antonio',
       C: 'Henderson',
       D: 'ahenderson2@mapquest.com',
       E: 'Male',
       F: '186.224.18.54' },
     { A: 4,
       B: 'Matthew',
       C: 'Jacobs',
       D: 'mjacobs3@hatena.ne.jp',
       E: 'Male',
       F: '71.115.204.8' },
     { A: 5,
       B: 'Jacqueline',
       C: 'Hawkins',
       D: 'jhawkins4@usatoday.com',
       E: 'Female',
       F: '112.161.144.113' },
     { A: 6,
       B: 'Betty',
       C: 'George',
       D: 'bgeorge5@cnbc.com',
       E: 'Female',
       F: '151.9.214.150' },
     { A: 7,
       B: 'Nicholas',
       C: 'Cole',
       D: 'ncole6@digg.com',
       E: 'Male',
       F: '130.113.34.123' },
     { A: 8,
       B: 'Christina',
       C: 'Fields',
       D: 'cfields7@icio.us',
       E: 'Female',
       F: '158.175.78.96' },
     { A: 9,
       B: 'John',
       C: 'Cole',
       D: 'jcole8@github.com',
       E: 'Male',
       F: '87.198.248.122' },
     { A: 10,
       B: 'Carolyn',
       C: 'Marshall',
       D: 'cmarshall9@acquirethisname.com',
       E: 'Female',
       F: '169.241.125.206' },
     { A: 11,
       B: 'Albert',
       C: 'Schmidt',
       D: 'aschmidta@imdb.com',
       E: 'Male',
       F: '82.36.174.49' },
     { A: 12,
       B: 'Lillian',
       C: 'Bennett',
       D: 'lbennettb@ca.gov',
       E: 'Female',
       F: '227.130.226.191' },
     { A: 13,
       B: 'Kathy',
       C: 'Payne',
       D: 'kpaynec@mozilla.org',
       E: 'Female',
       F: '189.92.180.236' },
     { A: 14,
       B: 'Jack',
       C: 'Ferguson',
       D: 'jfergusond@youku.com',
       E: 'Male',
       F: '237.228.12.35' },
     { A: 15,
       B: 'Jean',
       C: 'Gordon',
       D: 'jgordone@tinypic.com',
       E: 'Female',
       F: '82.238.48.246' },
     { A: 16,
       B: 'John',
       C: 'Clark',
       D: 'jclarkf@google.com',
       E: 'Male',
       F: '43.126.79.189' },
     { A: 17,
       B: 'Pamela',
       C: 'Gilbert',
       D: 'pgilbertg@china.com.cn',
       E: 'Female',
       F: '22.163.47.237' },
     { A: 18,
       B: 'Deborah',
       C: 'Banks',
       D: 'dbanksh@umn.edu',
       E: 'Female',
       F: '221.123.73.42' },
     { A: 19,
       B: 'Emily',
       C: 'Hamilton',
       D: 'ehamiltoni@craigslist.org',
       E: 'Female',
       F: '30.169.177.251' },
     { A: 20,
       B: 'Katherine',
       C: 'Jones',
       D: 'kjonesj@behance.net',
       E: 'Female',
       F: '228.11.87.66' },
     { A: 21,
       B: 'Ruby',
       C: 'Stanley',
       D: 'rstanleyk@w3.org',
       E: 'Female',
       F: '60.65.225.158' },
     { A: 22,
       B: 'Juan',
       C: 'Pierce',
       D: 'jpiercel@miitbeian.gov.cn',
       E: 'Male',
       F: '116.251.134.70' },
     { A: 23,
       B: 'Rachel',
       C: 'Long',
       D: 'rlongm@usnews.com',
       E: 'Female',
       F: '137.30.106.203' },
     { A: 24,
       B: 'Debra',
       C: 'Oliver',
       D: 'dolivern@yolasite.com',
       E: 'Female',
       F: '187.87.117.203' } ],
  sheet2:
   [ { A: 'id',
       B: 'first_name',
       C: 'last_name',
       D: 'email',
       E: 'gender',
       F: 'ip_address' },
     { A: 25,
       B: 'Jack',
       C: 'Bishop',
       D: 'jbishopo@businessinsider.com',
       E: 'Male',
       F: '154.11.84.148' },
     { A: 26,
       B: 'Alice',
       C: 'Cook',
       D: 'acookp@theatlantic.com',
       E: 'Female',
       F: '253.251.171.169' },
     { A: 27,
       B: 'Denise',
       C: 'Hart',
       D: 'dhartq@free.fr',
       E: 'Female',
       F: '41.7.18.202' },
     { A: 28,
       B: 'Susan',
       C: 'Oliver',
       D: 'soliverr@narod.ru',
       E: 'Female',
       F: '30.73.25.111' },
     { A: 29,
       B: 'Christopher',
       C: 'Watson',
       D: 'cwatsons@ibm.com',
       E: 'Male',
       F: '237.207.183.205' },
     { A: 30,
       B: 'Howard',
       C: 'Ray',
       D: 'hrayt@typepad.com',
       E: 'Male',
       F: '110.31.192.119' },
     { A: 31,
       B: 'Doris',
       C: 'Banks',
       D: 'dbanksu@tripod.com',
       E: 'Female',
       F: '93.158.23.15' },
     { A: 32,
       B: 'Tammy',
       C: 'Duncan',
       D: 'tduncanv@who.int',
       E: 'Female',
       F: '36.223.211.101' },
     { A: 33,
       B: 'Brandon',
       C: 'Nelson',
       D: 'bnelsonw@nsw.gov.au',
       E: 'Male',
       F: '149.230.247.47' },
     { A: 34,
       B: 'Janice',
       C: 'Banks',
       D: 'jbanksx@reverbnation.com',
       E: 'Female',
       F: '225.10.207.129' },
     { A: 35,
       B: 'Randy',
       C: 'Gardner',
       D: 'rgardnery@cdc.gov',
       E: 'Male',
       F: '136.250.243.202' },
     { A: 36,
       B: 'Denise',
       C: 'Burton',
       D: 'dburtonz@timesonline.co.uk',
       E: 'Female',
       F: '254.185.104.57' },
     { A: 37,
       B: 'Paul',
       C: 'Rogers',
       D: 'progers10@npr.org',
       E: 'Male',
       F: '188.219.107.207' },
     { A: 38,
       B: 'Johnny',
       C: 'Fernandez',
       D: 'jfernandez11@amazonaws.com',
       E: 'Male',
       F: '233.164.136.180' },
     { A: 39,
       B: 'Jane',
       C: 'Mason',
       D: 'jmason12@phpbb.com',
       E: 'Female',
       F: '156.240.141.240' },
     { A: 40,
       B: 'Scott',
       C: 'Day',
       D: 'sday13@prnewswire.com',
       E: 'Male',
       F: '154.188.18.107' },
     { A: 41,
       B: 'Philip',
       C: 'White',
       D: 'pwhite14@exblog.jp',
       E: 'Male',
       F: '73.100.195.152' },
     { A: 42,
       B: 'Kenneth',
       C: 'Duncan',
       D: 'kduncan15@people.com.cn',
       E: 'Male',
       F: '105.112.16.103' },
     { A: 43,
       B: 'Joseph',
       C: 'Price',
       D: 'jprice16@cmu.edu',
       E: 'Male',
       F: '33.92.219.103' },
     { A: 44,
       B: 'Edward',
       C: 'Howard',
       D: 'ehoward17@businessinsider.com',
       E: 'Male',
       F: '38.179.117.21' },
     { A: 45,
       B: 'Frances',
       C: 'Wells',
       D: 'fwells18@slashdot.org',
       E: 'Female',
       F: '75.126.73.137' },
     { A: 46,
       B: 'Ashley',
       C: 'Davis',
       D: 'adavis19@slideshare.net',
       E: 'Female',
       F: '73.140.223.76' },
     { A: 47,
       B: 'Clarence',
       C: 'Hicks',
       D: 'chicks1a@epa.gov',
       E: 'Male',
       F: '92.13.200.140' },
     { A: 48,
       B: 'Sharon',
       C: 'Stone',
       D: 'sstone1b@biblegateway.com',
       E: 'Female',
       F: '38.83.41.214' },
     { A: 49,
       B: 'Scott',
       C: 'Shaw',
       D: 'sshaw1c@senate.gov',
       E: 'Male',
       F: '84.180.189.90' },
     { A: 50,
       B: 'Susan',
       C: 'Miller',
       D: 'smiller1d@china.com.cn',
       E: 'Female',
       F: '244.232.244.90' } ] }

**Comment by DiegoZoracKy** [comment]
@naresh217 I deleted your last message because it seems to have real personal data from some people. But, from what I saw, it seems to be a valid json.

**Comment by naresh217** [comment]
I tried to validate it in http://jsonviewer.stack.hu and jsonlint.com both
says invalid format.
What i see was it generating data twice in the same file.
Thanks for deletions

**Comment by DiegoZoracKy** [comment]
@naresh217 Get the new version 1.4.0. You were right. When defining **outputJSON** both versions were being printed on stdout (JSON and raw Object Literal). Now the **outputJSON** is not needed anymore. I took the time to also make some improvements that were on my todo list, on the usage via CLI. 

From now on you can pass only the **sourceFile** option instead of the whole config in JSON format. Example:

```
$ convert-excel-to-json --sourceFile="tests/test-data.xlsx"
```

Also, it has now a better help section:

```
$ convert-excel-to-json --help
```

You can check more info about it here: https://github.com/DiegoZoracKy/convert-excel-to-json#cli



Thanks for opening this issue.

**Comment by naresh217** [comment]
Thanks this worked like an awesome

**Comment by DiegoZoracKy** [comment]
Great 🤘
