### ISSUE TITLE
Nest column with array or object?

### ISSUE THREAD

**Issue by thearabbit** [DiegoZoracKy/convert-excel-to-json#12]
Could use nest column `array, object` like this
```js
"aliases": [
    "stormagedden",
    "bob"
  ]
---
"address": {
      "street": "12 Beaver Court",
      "city": "Snowmass",
      "state": "CO",
      "zip": "81615"
    }
```

**Comment by DiegoZoracKy** [comment]
Hi @thearabbit, could you describe better the idea?

**Comment by thearabbit** [comment]
Like [excel-as-json](https://github.com/stevetarver/excel-as-json)

![image](https://user-images.githubusercontent.com/4495160/44341129-3929af80-a4b1-11e8-831a-bffd98c0142c.png)

**Comment by thearabbit** [comment]
thanks 👍
