### ISSUE TITLE
How to use with `Upload file: file[0]`?

### ISSUE THREAD

**Issue by thearabbit** [DiegoZoracKy/convert-excel-to-json#13]
I would like to convert from `upload excel file`
```js
      const files = event.target.files
      .....
      const result = excelToJson({
        sourceFile: file[0],
      })
```
But don't work

![image](https://user-images.githubusercontent.com/4495160/44320298-58055300-a46b-11e8-92a8-f7e1eaf9e26b.png)

**Comment by DiegoZoracKy** [comment]
Based on the log you sent, it seems that the error is not related to this module. Take a look at `readFileSync` is not a function. Are you trying to use it on the front-end?

**Comment by thearabbit** [comment]
Yes, now I know it use on Server!
but I not clear how to upload my excel file to Server `Meteor Method`.
I base on `Meteor JS`
```js
// Client
const files = event.target.files
Meteor.call('methodName', file[0], (err, res) => {
   
})
---
// Server
Meteor.methods({
   methodName(file){
       const json = excelToJson({
         sourceFile: file,
      })
      console.log(json)
   }
})
```
But not work, please help me (how to pass file[0] to server)

**Comment by DiegoZoracKy** [comment]
I would really help you if I could. But I don't know much about Meteor. I suggest you to forget about the conversion for a while, and to focus only on getting the uploaded file path on the server. Write a code where you will only `console.log` the received file path and then you try to move forward with the conversion. 

After you can get the uploaded file path on the server, if you still have a problem with the conversion, feel free to ping me here.

**Comment by thearabbit** [comment]
I tried to use `FileReader` via ` `Meteor forum to update file`
```
var reader = new FileReader()
      reader.addEventListener(
        'load',
        function() {
           Meteor.call('methodName', reader.result)
        },
        false
      )
      reader.readAsDataURL(file)
      // reader.readAsText(file)
      // reader.readAsArrayBuffer(file)
      // reader.readAsBinaryString(file)
```
but still not work

**Comment by thearabbit** [comment]
Other hand, could you example with 
- Rest API (Express)
- Axios (HTTP client)
Bc I could use this instead `Meteor Method`

**Comment by DiegoZoracKy** [comment]
See if the example section here can help you:

https://www.npmjs.com/package/express-fileupload

**Comment by thearabbit** [comment]
Now I use `Meteor File Upload`, and then read file to source
