### ISSUE TITLE
could I use the row[0]/header as prop name of object value?

### ISSUE THREAD

**Issue by thearabbit** [DiegoZoracKy/convert-excel-to-json#14]
![image](https://user-images.githubusercontent.com/4495160/44381304-d3cdd100-a539-11e8-871c-3edf087c81cf.png)

```
[
  {id: , name: , gender: , dob: , time:, amount: ...},
  {id: , name: , gender: , dob: , time:, amount: ...},
  {id: , name: , gender: , dob: , time:, amount: ...},
]

**Comment by thearabbit** [comment]
I can't use `column to key mapping`, bc sometime use changed order column.

**Comment by thearabbit** [comment]
Now work fine
```js
columnToKey: {
          '*': '{{columnHeader}}',
        },
```

**Comment by thearabbit** [comment]
Now work fine
```js
columnToKey: {
          '*': '{{columnHeader}}',
        },
```
I solved by all column, but I wold like to do any columns

**Comment by DiegoZoracKy** [comment]
Great! So, is everything ok now? Can we close this issue?

**Comment by ukankal** [comment]
How do we cleanse header values(like replace space, dots etc in header cells with _'s ) and still do columnToKeycolumnToKey: {
          '*': '{{columnHeader}}',
        }

**Comment by DiegoZoracKy** [comment]
Did you find error while running the module because those characters were written on the header, or do you just want to "clean" the keys found on the result object?

**Comment by DiegoZoracKy** [comment]
This module doesn't provide something on this sense. This should be a rule
of your application's domain. What you can do is to clean it yourself by
looping through all the keys with Object.keys().

**Comment by thearabbit** [comment]
Thanks for your reply.
How to solve?

**Comment by DiegoZoracKy** [comment]
Hi @thearabbit, how to solve what?

**Comment by thearabbit** [comment]
Now I use 
```js
columnToKey: {
		A: 'id',
		B: 'firstName'
	}
```
But don't good for me, when user change order of column name

**Comment by DiegoZoracKy** [comment]
By using:

```
columnToKey: {
"*": "{{columnHeader}}"
}
```

You could get all the keys, following what is written on the header, regardless of their order.

Search for "columnHeader" on the docs to see more about it.

**Comment by thearabbit** [comment]
I would like specific like this
```js
columnToKey: {
   "ID Column": "id",
   "First Name": "firstName",
   "Other Column": "other"
}
```

**Comment by DiegoZoracKy** [comment]
Take a look at the section: "Mapping columns to keys :: Special Variables
Cell Variables" 

It says:

"A value from a specific cell can be defined as a key name (e.g. { A: '{{A1}}' })..."

This one and the `{{columnHeader}} ` are closest solutions to what you want to achieve.

**Comment by thearabbit** [comment]
Thanks, Now I understand about this usage.
👍
