### ISSUE TITLE
Parsing time to string results in date

### ISSUE THREAD

**Issue by rxhl** [DiegoZoracKy/convert-excel-to-json#15]
I'm trying to parse an excel sheet where one of the columns is time viz. `5:15PM`, `7:10AM`. I can store these values successfully as strings just by doing `myTimeVar.toString()`.

However, when the time value has a space in between e.g. `5:15 PM` and `7:10 AM`, the `toString()` method returns a full blown date object as string. For instance, `myTimeVar.toString()` prints `Sat Dec 30 1899 16:15:00 GMT-0500 (Eastern Standard Time)` where myTimeVar is `5:15 PM` (with a space in between time and PM).

I even tried avoiding `toString()` and using `String()` but no success.

More details [here](https://stackoverflow.com/questions/52106271/parsing-time-to-string-results-in-date).

**Comment by DiegoZoracKy** [comment]
Currently, all cells of type `date` on Excel are returned as a `Date`
object on JS.

Could you try to select these cells and force its data type to text/string
on Excel? It seems that your spreadsheet is automatically setting the type
to date when it has a space, because in this way it is inferring this type.
Probably those cells are defined as General on Excel.

**Comment by DiegoZoracKy** [comment]
Something new on this case?

**Comment by rxhl** [comment]
Those cells are indeed 'General' in Excel. When I force change their type to 'Text', the time string turns into a number viz. `5:15 PM` becomes `0.71875`. Do you know how to turn off this automatic conversion?

**Comment by DiegoZoracKy** [comment]
Yes, excel has this kinda of weird behavior. Try to copy all the values of this column to the Notepad (or other text editor), select the entire column and change its type to Text, then paste back the values from Notepad. After that, hopefully you will have all the original data as text.

**Comment by rxhl** [comment]
Thanks, it did work out. As you can imagine, parsing hundreds of sheets this way might be tedious. Please do post if you have any other idea. Thanks again for the great library.

**Comment by JaviPG** [comment]
Anybody found solution for convert date fields to string fields?

Currently I'm try solve it. If can i find way I'll share it with you.
