### ISSUE TITLE
Missing required _config :: function (obj)

### ISSUE THREAD

**Issue by joelsantosjunior** [DiegoZoracKy/convert-excel-to-json#16]
When I try to convert a file, an error is returned

![image](https://user-images.githubusercontent.com/8531514/45511813-639b1f80-b774-11e8-8eda-73c8adc49c9b.png)

![image](https://user-images.githubusercontent.com/8531514/45511790-54b46d00-b774-11e8-9e24-367f928495a3.png)

PS: "path" is a valid file path

node v8.10.0
npm 3.5.2

**Comment by DiegoZoracKy** [comment]
Which version of the lib are you using?

**Comment by joelsantosjunior** [comment]
1.4.0

**Comment by DiegoZoracKy** [comment]
Can you show me more of your code (hiding sensitive information)? This
version is being used for two months already and there wasn't a case like
that showing up.

**Comment by DiegoZoracKy** [comment]
Any news here @joelsantosjunior?  I still couldn't reproduce your case.

**Comment by joelsantosjunior** [comment]
I was able to solve the problem using another library that was already in the project, thanks!
