### ISSUE TITLE
Wrap strings in double quotes

### ISSUE THREAD

**Issue by strayguevara** [DiegoZoracKy/convert-excel-to-json#18]
JSON is currently being output as follows:

`{ example: 
   [ { id: 1, category: 'fruit', name: 'pear', price: 2.5 },
     { id: 2, category: 'vegetable', name: 'potato', price: 2.5 },
     { id: 3, category: 'vegetable', name: 'zuchinni', price: 2.5 },
     { id: 4, category: 'fruit', name: 'banana', price: 1.5 },
     { id: 5, category: 'fruit', name: 'apple', price: 1.5 },
     { id: 6, category: 'friut', name: 'strawberry', price: 2.5 },
     { id: 7, category: 'fruit', name: 'mango', price: 3 },
     { id: 8, category: 'vegetable', name: 'carrot', price: 4.5 } ] }`

How do I wrap strings in double quotes so that is valid JSON?  Desired output:

`{ "example": 
   [ { "id": 1, "category": "fruit", "name": "pear", "price": 2.5 },
     { "id": 2, "category": "vegetable", "name": "potato", "price": 2.5 },
     { "id": 3, "category": "vegetable", "name": "zuchinni", "price": 2.5 },
     { "id": 4, "category": "fruit", "name": "banana", "price": 1.5 },
     { "id": 5, "category": "fruit", "name": "apple", "price": 1.5 },
     { "id": 6, "category": "friut", "name": "strawberry", "price": 2.5 },
     { "id": 7, "category": "fruit", "name": "mango", "price": 3 },
     { "id": 8, "category": "vegetable", "name": "carrot", "price": 4.5 } ] }`

**Comment by DiegoZoracKy** [comment]
Which version are you using? If it's a version lower than the current one (1.4.1) try to update it.  Currently, when called via CLI, the output is being converted to JSON.

**Comment by strayguevara** [comment]
Hi Diego

I'm using v1.4.1 but my output is as above.  My .js file is configured as follows:

`'use strict';
const excelToJson = require('convert-excel-to-json');

const result = excelToJson({
	sourceFile: './file.xlsx',
	header:{
	    rows: 1 
	},
	columnToKey: {
      '*': '{{columnHeader}}',
    }
});

var fs = require('fs');
var util = require('util');
fs.writeFileSync('./data.json', util.inspect(result) , 'utf-8');
console.log(result);`

**Comment by DiegoZoracKy** [comment]
I see. The result of this lib, when not being executed via CLI, is indeed an Object Literal and not a JSON. In your specific case, you want to convert it to a JSON, so you can do `JSON.stringify(result)` to accomplish that.

**Comment by strayguevara** [comment]
Awesome, thank you.

**Comment by DiegoZoracKy** [comment]
🤘
