### ISSUE TITLE
sheet[cell].v.trim is not a function

### ISSUE THREAD

**Issue by aTewan** [DiegoZoracKy/convert-excel-to-json#2]
I don't know why when I try to convert some sheets, I got an error : 
```

            rowData[columnData] = (sheet[cell].t == 'n') ? sheet[cell].w.trim()
: sheet[cell].v.trim();

                ^

TypeError: sheet[cell].v.trim is not a function
    at parseSheet (C:\node_modules\convert-excel-to
-json\lib\convert-excel-to-json.js:92:97)
    at sheetsToGet.forEach.sheet (C:\node_modules\c
onvert-excel-to-json\lib\convert-excel-to-json.js:125:38)
    at Array.forEach (native)
    at convertExcelToJson (C:\node_modules\convert-
excel-to-json\lib\convert-excel-to-json.js:120:21)
    at convertXLS2JSON (C:\test.js:30:15)
    at Server.<anonymous> (C:\test.js:200:2)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1288:10)
```

**Comment by DiegoZoracKy** [comment]
Hi @aTewan,

I made a fix for that. Can you try with the latest version and tell me if everything went well?

**Comment by aTewan** [comment]
It looks perfect, thank you so much !

**Comment by DiegoZoracKy** [comment]
Good!

Can you tell me what kind of data were you extracting from the spreadsheet?
Just to know about this case that i hadn't thought about yet.

**Comment by aTewan** [comment]
I think it's because on the excel file i tried to convert, there is on several cells, some errors when a function was applied on this (i convert xlsm into xlsx), these errors filled the cell with "#N/A" because "unavailable value". But after the conversion "#N/A" result into 42.

**Comment by DiegoZoracKy** [comment]
Got it! Thanks for the extra info @aTewan .
