### ISSUE TITLE
Uncaught TypeError: fs.readFileSync is not a function

### ISSUE THREAD

**Issue by Anoi** [DiegoZoracKy/convert-excel-to-json#28]
When i used by example, throws error .   Uncaught TypeError: fs.readFileSync is not a function 
Help!

**Comment by DiegoZoracKy** [comment]
Which Node.js version are you using?

**Comment by Anoi** [comment]
v10.13

**Comment by DiegoZoracKy** [comment]
Are you trying to run it on front-end? Because this module works only on back-end.

**Comment by JakeHadley** [comment]
I am trying to run this in a react-native application and I'm getting this error. Not going to work then?
