### ISSUE TITLE
Get worksheet list.

### ISSUE THREAD

**Issue by gabhishekprdxn** [DiegoZoracKy/convert-excel-to-json#32]
Hi, 
Is there any method to find all worksheets name from the source file(excel file)

**Comment by gabhishekprdxn** [comment]
There is an issue like if I passed a Worksheet name, that does not exist in the source file. Then also return blank data. I think it should be handled by this lib. Let me know when it will be updated.

**Comment by DiegoZoracKy** [comment]
You can get all sheets names from the object returned by the lib. `Object.keys(resultObjectFromExcelToJson)` will give you that.

**Comment by gabhishekprdxn** [comment]
Thanks!! I got it.
