### ISSUE TITLE
Error: Cannot find module 'convert-excel-to-json' after building electron app

### ISSUE THREAD

**Issue by killerart** [DiegoZoracKy/convert-excel-to-json#37]
I am making an electron app and your realization of excel-to-json fits me the most. It works just fine if I run the app with node.js, but when I build it and try to run, it can't find it
![Annotation 2020-02-02 162636](https://user-images.githubusercontent.com/48909985/73609670-cd6dd080-45d8-11ea-9bda-53202dafe7ad.jpg)

**Comment by killerart** [comment]
Sorry, just had to include it in dependencies in package.json

**Comment by DiegoZoracKy** [comment]
👍👍
