### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'https://[FILE_URL]'

### ISSUE THREAD

**Issue by rmoylan** [DiegoZoracKy/convert-excel-to-json#38]
When targeting the file locally, I  have no issue, but when I target the server hosted version, I  get the following error. Is there something different I  need to do when the file is hosted?

`Error: ENOENT: no such file or directory, open 'https://[FILE_URL]'`

This is my code
`const movementOrders = excelToJson({
			sourceFile: args.url,
			sheets: ['Data']
		});`

Thanks!

**Comment by DiegoZoracKy** [comment]
Hi @rmoylan,

Yes, you would need to download the file first, and then when the download is finished, you can pass the local file path to the lib. It's not prepared to handle URLs.

**Comment by rmoylan** [comment]
@DiegoZoracKy Got it thanks!
