### ISSUE TITLE
how to change sheet name 

### ISSUE THREAD

**Issue by aboodrazeq** [DiegoZoracKy/convert-excel-to-json#48]
everything ok I read all data and the header but I want to remove the sheet or change the name of it
thank you

**Comment by DiegoZoracKy** [comment]
Hi @aboodrazeq maybe this config is what you are looking for:

https://github.com/DiegoZoracKy/convert-excel-to-json#only-to-specific-sheets

**Comment by Sanotsu** [comment]
Maybe like a sheet named "sheet1", after convert to JSON, the name changed to "newSheet"? Thx.

**Comment by Marcosmaliki** [comment]
I need this too, sheet name can be dynamic

**Comment by Marcosmaliki** [comment]
Never mind. We can use `Object.keys(result)` to get the sheet name then use it to filter the response like `result[Object.keys(result)[0]]`

**Comment by DiegoZoracKy** [comment]
I believe that the way @Marcosmaliki brought would be the best one to go. Although we can develop this as a new feature, it's so simple to be done on a post processing snippet of code that maybe isn't worth to think of it as a new feature. I'm going to close this issue but if someone wants to get back to this conversation we can reopen it.
