### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by bhavarajus** [DiegoZoracKy/convert-excel-to-json#5]
How to handle if any error occurs at the time of conversion? Thank you.

**Comment by DiegoZoracKy** [comment]
This function is executed in a "sync" way, so wrapping it within a `try...catch` will allow you to catch any error that might happen.

Out of curiosity, are you currently facing  some kind of error while executing it?

**Comment by bhavarajus** [comment]
Thank you the error I was getting is as follows

> TypeError: Cannot read property 't' of undefined

I am fairly new to developing could you give me an example how to try and catch error.

Thank you

**Comment by DiegoZoracKy** [comment]
Can you post here a code snippet showing how you are calling the function?
To check if the arguments are correct.

A `try...catch` works as follows:

`
try {
    someFunction();
} catch(ex) {
    console.error(ex);
}

// in case someFunction()  results in error, the following will still be
executed
console.log('this code will be executed');

**Comment by bhavarajus** [comment]
Ya sure here below is what I am doing. By the way what I am doing is in javascript.
`var excelToJson = require('convert-excel-to-json');
var uploadData;
var result = excelToJson({
                    sourceFile: newFileName,
                    header: {
                        rows: 1
                    },
                    columnToKey: {
                        '*': '{{columnHeader}}'
                    }
                });
                if (result) {
                    uploadData = result[Object.keys(result)];
                } else {
                    response.errorData = "Format error";
                    callback(response.errorData);
                }
                 var callback = function(recordInfo) {
                    response.records.push(recordInfo);                    
                    if (uploadData.length == response.records.length) {
                         res.send(response);
                    }
                 };`

**Comment by DiegoZoracKy** [comment]
hey @bhavarajus, did you solve your issue?

**Comment by DiegoZoracKy** [comment]
Feel free to open that issue again in case you need it.
