### ISSUE TITLE
Why it doesn't handle date types?

### ISSUE THREAD

**Issue by ayush12234** [DiegoZoracKy/convert-excel-to-json#6]
I was converting a date and it got replaced by some number.

**Comment by DiegoZoracKy** [comment]
Hey @ayush12234, thanks for bringing that up. Check with the new version, 1.3.0, and tell me if now you have the date handled as expected.

**Comment by ayush12234** [comment]
Thanks @DiegoZoracKy . Its working good now.

**Comment by DiegoZoracKy** [comment]
👍
