### ISSUE TITLE
Issue with larger files

### ISSUE THREAD

**Issue by rugged-service** [DiegoZoracKy/convert-excel-to-json#8]
I'm having an issue processing large file of ~50mb. Could this be something I'm doing wrong or do you know if the package allows processing of very large files?

**Comment by DiegoZoracKy** [comment]
What is the error that you are facing? Can you post the error message here?

**Comment by DiegoZoracKy** [comment]
HI @rugged-service,

Did you managed to process your large file? Can we close this issue?
